### ISSUE TITLE
ADF prototype only accounting for one covalent bond

### ISSUE THREAD

**Issue by davidz873** [davidz873/CMSUNLV#6]
@qzhu2017 

Can you take a look at my most recent commit?  The screening for whether a bond is made is only returning atomic triples with bond angles of 120 degrees for the current material.

**Comment by davidz873** [comment]
@qzhu2017 

What is concerning me is that pymatgen states there are 90 degree and 120 degree bonds.  The adf prototype is only accounting for the 120 degree bonds

**Comment by qzhu2017** [comment]
@davidz873 
I am sure there is not 90 degree angle in graphite.
